//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Tour
{
    using System;
    using System.Collections.Generic;
    
    public partial class DASHBOARD
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> BookTime { get; set; }
        public Nullable<int> IDCustomer { get; set; }
        public Nullable<int> IDTour { get; set; }
        public string IsPaid { get; set; }
        public Nullable<int> NumberOfTicket { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual TOUR TOUR { get; set; }
    }
}
