//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Tour
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKET
    {
        public int ID { get; set; }
        public int TourID { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Number { get; set; }
        public string Sale { get; set; }
    
        public virtual TOUR TOUR { get; set; }
    }
}
